version: "3.8"
services:
    ansible:
        build:
            context: .
            dockerfile: Dockerfile
        command: tail -f /dev/null
        volumes:
            - ./playbook:/var/www/playbook
